#!/bin/bash
export CLASS_LOADER_PATH="./src/classLoader.php"
export INCLUDE_DIRS="./src/model ./src/controller"

echo "<?php" >  $CLASS_LOADER_PATH
echo "/* @generated by ../generate-loader.sh */" >> $CLASS_LOADER_PATH
find $INCLUDE_DIRS | grep .php | sed "s/^.\/src//" | awk '{print "require_once(__DIR__ . \""$1"\");"}' >> $CLASS_LOADER_PATH

